dashboard/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required, permission_required

from . import views
from .user_views import AdministratorListView, AdministratorCreationView, AdministratorUpdateView, AdministratorDeleteView
from .user_views import ChannelListView, ChannelCreationView, ChannelUpdateView, ChannelDeleteView
from .user_views import TeacherListView, TeacherCreationView, TeacherUpdateView, TeacherDeleteView
from .user_views import StudentListView, StudentCreationView, StudentUpdateView, StudentDeleteView
from .user_views import StudentDetailView
from .user_views import SelfUpdateView
from .views import AdministratorOverview
from .views import ChannelRelationshipListView, ChannelRelationshipCreationView, ChannelRelationshipUpdateView, ChannelRelationshipDeleteView
from .views import MentoringRelationshipListView, MentoringRelationshipCreationView, MentoringRelationshipUpdateView, MentoringRelationshipDeleteView
from .views import MentoringRecordListView, MentoringRecordCreationView, MentoringRecordUpdateView, MentoringRecordDetailView, MentoringRecordDeleteView
from .views import MissionListView, MissionCreationView, MissionUpdateView, MissionDetailView, MissionDeleteView
from .views import SchoolApplicationCountryListView, SchoolApplicationCountryCreationView, SchoolApplicationCountryUpdateView, SchoolApplicationCountryDeleteView
from .views import SchoolApplicationSchoolListView, SchoolApplicationSchoolCreationView, SchoolApplicationSchoolUpdateView, SchoolApplicationSchoolDeleteView
from .views import SchoolApplicationCollegeListView, SchoolApplicationCollegeCreationView, SchoolApplicationCollegeUpdateView, SchoolApplicationCollegeDeleteView
from .views import SchoolApplicationMajorListView, SchoolApplicationMajorCreationView, SchoolApplicationMajorUpdateView, SchoolApplicationMajorDeleteView
from .views import SchoolApplicationDegreeListView, SchoolApplicationDegreeCreationView, SchoolApplicationDegreeUpdateView, SchoolApplicationDegreeDeleteView
from .views import SchoolApplicationDegreeDetailView

app_name = 'dashboard'
urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', login_required(views.overview), name='overview'),

    url(r'overview/administrator/$', 
        login_required(permission_required('dashboard.view_administrator')(
            AdministratorOverview.as_view())), 
        name='AdministratorOverview'),

    url(r'administrator/$', 
        login_required(permission_required('dashboard.view_administrator')(
            AdministratorListView.as_view())), 
        name='AdministratorListView'),
    url(r'administrator/creation/$', 
        login_required(permission_required('dashboard.add_administrator')(
            AdministratorCreationView.as_view())), 
        name='AdministratorCreationView'),
    url(r'administrator/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_administrator')(
            AdministratorUpdateView.as_view())), 
        name='AdministratorUpdateView'),
    url(r'administrator/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_administrator')(
            AdministratorDeleteView.as_view())), 
        name='AdministratorDeleteView'),

    url(r'channel/$', 
        login_required(permission_required('dashboard.view_channel')(
            ChannelListView.as_view())), 
        name='ChannelListView'),
    url(r'channel/creation/$', 
        login_required(permission_required('dashboard.add_channel')(
            ChannelCreationView.as_view())), 
        name='ChannelCreationView'),
    url(r'channel/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_channel')(
            ChannelUpdateView.as_view())), 
        name='ChannelUpdateView'),
    url(r'channel/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_channel')(
            ChannelDeleteView.as_view())), 
        name='ChannelDeleteView'),

    url(r'teacher/$', 
        login_required(permission_required('dashboard.view_teacher')(
            TeacherListView.as_view())), 
        name='TeacherListView'),
    url(r'teacher/creation/$', 
        login_required(permission_required('dashboard.add_teacher')(
            TeacherCreationView.as_view())), 
        name='TeacherCreationView'),
    url(r'teacher/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_teacher')(
            TeacherUpdateView.as_view())), 
        name='TeacherUpdateView'),
    url(r'teacher/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_teacher')(
            TeacherDeleteView.as_view())), 
        name='TeacherDeleteView'),

    url(r'student/$', 
        login_required(permission_required('dashboard.view_student')(
            StudentListView.as_view())), 
        name='StudentListView'),
    url(r'student/(?P<pk>[0-9]+)/detail/$', 
        login_required(permission_required('dashboard.view_student')(
            StudentDetailView.as_view())), 
        name='StudentDetailView'),
    url(r'student/creation/$', 
        login_required(permission_required('dashboard.add_student')(
            StudentCreationView.as_view())), 
        name='StudentCreationView'),
    url(r'student/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_student')(
            StudentUpdateView.as_view())), 
        name='StudentUpdateView'),
    url(r'student/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_student')(
            StudentDeleteView.as_view())), 
        name='StudentDeleteView'),

    url(r'channel/relationship/$', 
        login_required(permission_required('dashboard.view_channelrelationship')(
            ChannelRelationshipListView.as_view())), 
        name='ChannelRelationshipListView'),
    url(r'channel/relationship/creation/$', 
        login_required(permission_required('dashboard.add_channelrelationship')(
            ChannelRelationshipCreationView.as_view())), 
        name='ChannelRelationshipCreationView'),
    url(r'channel/relationship/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_channelrelationship')(
            ChannelRelationshipUpdateView.as_view())), 
        name='ChannelRelationshipUpdateView'),
    url(r'channel/relationship/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_channelrelationship')(
            ChannelRelationshipDeleteView.as_view())), 
        name='ChannelRelationshipDeleteView'),

    url(r'mentoring/relationship/$', 
        login_required(permission_required('dashboard.view_mentoringrelationship')(
            MentoringRelationshipListView.as_view())), 
        name='MentoringRelationshipListView'),
    url(r'mentoring/relationship/creation/$', 
        login_required(permission_required('dashboard.add_mentoringrelationship')(
            MentoringRelationshipCreationView.as_view())), 
        name='MentoringRelationshipCreationView'),
    url(r'mentoring/relationship/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_mentoringrelationship')(
            MentoringRelationshipUpdateView.as_view())), 
        name='MentoringRelationshipUpdateView'),
    url(r'mentoring/relationship/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_mentoringrelationship')(
            MentoringRelationshipDeleteView.as_view())), 
        name='MentoringRelationshipDeleteView'),

    url(r'mentoring/record/$', 
        login_required(permission_required('dashboard.view_mentoringrecord')(
            MentoringRecordListView.as_view())), 
        name='MentoringRecordListView'),
    url(r'mentoring/record/creation/$', 
        login_required(permission_required('dashboard.add_mentoringrecord')(
            MentoringRecordCreationView.as_view())), 
        name='MentoringRecordCreationView'),
    url(r'mentoring/record/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_mentoringrecord')(
            MentoringRecordUpdateView.as_view())), 
        name='MentoringRecordUpdateView'),
    url(r'mentoring/record/(?P<pk>[0-9]+)/detail/$', 
        login_required(permission_required('dashboard.view_mentoringrecord')(
            MentoringRecordDetailView.as_view())), 
        name='MentoringRecordDetailView'),
    url(r'mentoring/record/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_mentoringrecord')(
            MentoringRecordDeleteView.as_view())), 
        name='MentoringRecordDeleteView'),

    url(r'mission/$', 
        login_required(permission_required('dashboard.view_mission')(
            MissionListView.as_view())), 
        name='MissionListView'),
    url(r'mission/creation/$', 
        login_required(permission_required('dashboard.add_mission')(
            MissionCreationView.as_view())), 
        name='MissionCreationView'),
    url(r'mission/(?P<pk>[0-9]+)/update/$', 
        login_required(permission_required('dashboard.change_mission')(
            MissionUpdateView.as_view())), 
        name='MissionUpdateView'),
    url(r'mission/(?P<pk>[0-9]+)/detail/$', 
        login_required(permission_required('dashboard.view_mission')(
            MissionDetailView.as_view())), 
        name='MissionDetailView'),
    url(r'mission/(?P<pk>[0-9]+)/delete/$', 
        login_required(permission_required('dashboard.delete_mission')(
            MissionDeleteView.as_view())), 
        name='MissionDeleteView'),

    url(r'school_application/country/$', 
        login_required(permission_required('dashboard.view_applycountry')(
            SchoolApplicationCountryListView.as_view())), 
        name='SchoolApplicationCountryListView'),
    url(r'school_application/country/creation/$', 

index/urls.py
from . import views
from django.conf.urls import url, include

app_name = 'index'
urlpatterns = [
    url(r'^$', views.about_us, name='about_us'),
]

younglights/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import reverse, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('index:about_us'))),
    url(r'^index/', include('index.urls')),
    url(r'^dashboard/', include('dashboard.urls')),

    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
]

templates/dashboard/channel_list.html
{% extends 'dashboard/dashboard.html' %}
{% block content %}
<div class="am-g">
	<div class="am-u-sm-12 am-u-md-6">
		<div class="am-btn-toolbar">
			<div class="am-btn-group am-btn-group-xs">
				<a class="am-btn am-btn-default" href="{{ page_add }}"><span class="am-icon-plus"></span> 新增</a>
			</div>
		</div>
	</div>
	<div class="am-u-sm-12 am-u-md-3">
		<form class="am-form" method="get" action="">
			<div class="am-input-group am-input-group-sm">
				<input type="text" class="am-form-field" value="{{search_text}}" name="search_text">
				<span class="am-input-group-btn">
					<input class="am-btn am-btn-default" type="submit" name="submit" value="搜索"/>
				</span>
			</div>
		</form>
	</div>
</div>

<div class="am-g">
	<div class="am-u-sm-12">
		<table class="am-table am-table-striped am-table-hover table-main">
			<thead>
				<tr>
					<th>名称</th>
					<th>电话</th>
					<th class="am-hide-sm-only">正在辅导人数</th>
					<th class="am-hide-sm-only">辅导完成人数</th>
					<th>对接人</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
				{% for user in object_list %}
				<tr>
					<td>{{ user.userprofile.channel_name }}</td>
					<td>{{ user.userprofile.phone }}</td>
					<td class="am-hide-sm-only">{{ user.userprofile.mentoring_count }}</td>
					<td class="am-hide-sm-only">{{ user.userprofile.mentoring_completed_count }}</td>
					<td>{{ user.userprofile.contact_name }}</td>
					<td>
						<div class="am-btn-toolbar">
							<div class="am-btn-group am-btn-group-xs">
								<a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="{% url 'dashboard:ChannelUpdateView' user.id %}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
								<a class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only" href="{% url 'dashboard:ChannelDeleteView' user.id %}"><span class="am-icon-trash-o"></span> 删除</a>
							</div>
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "dashboard/paginator.html" %}
	</div>
</div>
{% endblock %}

templates/dashboard/channel_relationship_list.html
{% extends 'dashboard/dashboard.html' %}
{% block content %}
<div class="am-g">
	<div class="am-u-sm-12 am-u-md-6">
		<div class="am-btn-toolbar">
			<div class="am-btn-group am-btn-group-xs">
				<a class="am-btn am-btn-default" href="{{ page_add }}"><span class="am-icon-plus"></span> 新增</a>
			</div>
		</div>
	</div>
	<div class="am-u-sm-12 am-u-md-3">
		<form class="am-form" method="get" action="">
			<div class="am-input-group am-input-group-sm">
				<input type="text" class="am-form-field" value="{{search_text}}" name="search_text">
				<span class="am-input-group-btn">
					<input class="am-btn am-btn-default" type="submit" name="submit" value="搜索"/>
				</span>
			</div>
		</form>
	</div>
</div>

<div class="am-g">
	<div class="am-u-sm-12">
		<table class="am-table am-table-striped am-table-hover table-main">
			<thead>
				<tr>
					<th>渠道</th>
					<th>学生</th>
					<th class="am-hide-sm-only">创建日期</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
				{% for object in object_list %}
				<tr>
					<td>{{ object.channel.userprofile.channel_name }}</td>
					<td>{{ object.student.userprofile.chinese_name }}</td>
					<td class="am-hide-sm-only">{{ object.added_datetime }}</td>
					<td>
						<div class="am-btn-toolbar">
							<div class="am-btn-group am-btn-group-xs">
								<a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="{% url 'dashboard:ChannelRelationshipUpdateView' object.id %}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
								<a class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only" href="{% url 'dashboard:ChannelRelationshipDeleteView' object.id %}"><span class="am-icon-trash-o"></span> 删除</a>
							</div>
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "dashboard/paginator.html" %}
	</div>
</div>
{% endblock %}

templates/dashboard/mentoring_record_list.html
{% extends 'dashboard/dashboard.html' %}
{% block content %}
<form class="am-form" method="get" action="">
	<div class="am-g">
		{% if request.user.groups.first.name == "管理员" %}
		<div class="am-u-sm-12 am-u-md-6">
			<div class="am-btn-toolbar">
				<div class="am-btn-group am-btn-group-xs">
					<a class="am-btn am-btn-default" href="{{ page_add }}"><span class="am-icon-plus"></span> 新增</a>
				</div>
			</div>
		</div>
		{% endif %}
		<div class="am-u-sm-12 am-u-md-3">
			<div class="am-input-group am-input-group-sm">
				<input type="text" class="am-form-field" value="{{search_text}}" name="search_text">
				<span class="am-input-group-btn">
					<input class="am-btn am-btn-default" type="submit" name="submitBtn" value="搜索"/>
				</span>
			</div>
		</div>
	</div>

	<div class="am-g">
		<div class="am-u-sm-12">
			<table class="am-table am-table-striped am-table-hover table-main">
				<thead>
					<tr>
						{% if request.user.groups.first.name == "管理员" %}
						<th>
							<select name="teacher_id" data-am-selected="{btnWidth: '70%', btnSize: 'sm'}" onChange="form.submit();">
								{% if query_teachers|length > 1 %}
								<option value="all">全部</option>
								{% endif %}
								{% for t in query_teachers %}
								<option value="{{t.id}}" {% if teacher_id == t.id|slugify %}selected="selected"{% endif %}>{{ t.userprofile.chinese_name }}</option>
								{% endfor %}
							</select>
						</th>
						{% endif %}
						<th>
							<select name="student_id" data-am-selected="{btnWidth: '70%', btnSize: 'sm'}" onChange="form.submit();">
								{% if query_students|length > 1 %}
								<option value="all">全部</option>
								{% endif %}
								{% for s in query_students %}
								<option value="{{s.id}}" {% if student_id == s.id|slugify %}selected="selected"{% endif %}>{{ s.userprofile.chinese_name }}</option>
								{% endfor %}
							</select>
						</th>
						<th class="am-hide-sm-only"></th>
						<th class="am-hide-sm-only"></th>
						<th class="am-hide-sm-only">{{ query_mentoring_time }}</th>
						<th></th>
					</tr>
					<tr>
						{% if request.user.groups.first.name == "管理员" %}
						<th>导师姓名</th>
						{% endif %}
						<th>学生姓名</th>
						<th class="am-hide-sm-only">内容</th>
						<th class="am-hide-sm-only">辅导日期</th>
						<th class="am-hide-sm-only">辅导时长</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
					{% for object in object_list %}
					<tr>
						{% if request.user.groups.first.name == "管理员" %}
						<td>{{ object.teacher.userprofile.chinese_name }}</td>
						{% endif %}
						<td>{{ object.student.userprofile.chinese_name }}</td>
						<td class="am-hide-sm-only">{{ object.content|truncatechars:15 }}</td>
						<td class="am-hide-sm-only">{{ object.mentoring_date }}</td>
						<td class="am-hide-sm-only">{{ object.mentoring_time }}</td>
						<td>
							<div class="am-btn-toolbar">
								<div class="am-btn-group am-btn-group-xs">
									<a class="am-btn am-btn-default am-btn-xs" href="{% url 'dashboard:MentoringRecordDetailView' object.id %}"><span class="am-icon-search"></span> 查看</a>
									{% if request.user.groups.first.name == "管理员" or request.user.groups.first.name == "导师" %}
									<a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="{% url 'dashboard:MentoringRecordUpdateView' object.id %}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
									<a class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only" href="{% url 'dashboard:MentoringRecordDeleteView' object.id %}"><span class="am-icon-trash-o"></span> 删除</a>
									{% endif %}
								</div>
							</div>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include "dashboard/paginator.html" %}
		</div>
	</div>
</form>
{% endblock %}

templates/dashboard/mission_list.html
{% extends 'dashboard/dashboard.html' %}
{% block content %}
<div class="am-g">
	<div class="am-u-sm-12 am-u-md-6">
		<div class="am-btn-toolbar">
			<div class="am-btn-group am-btn-group-xs">
				{% if request.user.groups.first.name != "学生" %}
				<a class="am-btn am-btn-default" href="{{ page_add }}"><span class="am-icon-plus"></span> 新增</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="am-u-sm-12 am-u-md-3">
		<form class="am-form" method="get" action="">
			<div class="am-input-group am-input-group-sm">
				<input type="text" class="am-form-field" value="{{search_text}}" name="search_text">
				<span class="am-input-group-btn">
					<input class="am-btn am-btn-default" type="submit" name="submit" value="搜索"/>
				</span>
			</div>
		</form>
	</div>
</div>

<div class="am-g">
	<div class="am-u-sm-12">
		<table class="am-table am-table-striped am-table-hover table-main">
			<thead>
				<tr>
					<th>标题</th>
					<th class="am-hide-sm-only">任务期限</th>
					{% if request.user.groups.first.name != "学生" %}
					<th>学生姓名</th>
					{% endif %}
					<th>导师姓名</th>
					<th class="am-hide-sm-only">创建日期</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
				{% for object in object_list %}
				<tr>
					<td>{{ object.title }}</td>
					<td class="am-hide-sm-only">{{ object.end_date }}</td>
					{% if request.user.groups.first.name != "学生" %}
					<td>{{ object.student.userprofile.chinese_name }}</td>
					{% endif %}
					<td>{{ object.teacher.userprofile.chinese_name }}</td>
					<td class="am-hide-sm-only">{{ object.added_datetime }}</td>
					<td>
						<div class="am-btn-toolbar">
							<div class="am-btn-group am-btn-group-xs">
								<a class="am-btn am-btn-default am-btn-xs" href="{% url 'dashboard:MissionDetailView' object.id %}"><span class="am-icon-search"></span> 查看</a>
								{% if request.user.groups.first.name != "学生" %}
								<a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="{% url 'dashboard:MissionUpdateView' object.id %}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
								<a class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only" href="{% url 'dashboard:MissionDeleteView' object.id %}"><span class="am-icon-trash-o"></span> 删除</a>
								{% endif %}
							</div>
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "dashboard/paginator.html" %}
	</div>
</div>
{% endblock %}

templates/dashboard/student_list.html
{% extends 'dashboard/dashboard.html' %}
{% block content %}
<div class="am-g">
	<div class="am-u-sm-12 am-u-md-6">
		<div class="am-btn-toolbar">
			<div class="am-btn-group am-btn-group-xs">
				{% if request.user.groups.first.name == "管理员" %}
				<a class="am-btn am-btn-default" href="{{ page_add }}"><span class="am-icon-plus"></span> 新增</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="am-u-sm-12 am-u-md-3">
		<form class="am-form" method="get" action="">
			<div class="am-input-group am-input-group-sm">
				<input type="text" class="am-form-field" value="{{search_text}}" name="search_text">
				<span class="am-input-group-btn">
					<input class="am-btn am-btn-default" type="submit" name="submit" value="搜索"/>
				</span>
			</div>
		</form>
	</div>
</div>

<div class="am-g">
	<div class="am-u-sm-12">
		<table class="am-table am-table-striped am-table-hover table-main">
			<thead>
				<tr>
					<th>姓名</th>
					<th>学校</th>
					<th>电话</th>
					<th>电邮</th>
					<th>辅导状态</th>
					<th>上次辅导时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
				{% for user in object_list %}
				<tr>
					<td>{{user.userprofile.chinese_name}}</td>
					<td>{{ user.userprofile.school }}</td>
					<td>{{ user.userprofile.phone }}</td>
					<td class="am-hide-sm-only">{{ user.email }}</td>
					<td class="am-hide-sm-only">
						{% if user.userprofile.is_mentoring %}辅导中{% else %}辅导完成{% endif %}
					</td>
					<td class="am-hide-sm-only">{{ user.userprofile.last_mentoring_record_date }}</td>
					<td>
						<div class="am-btn-toolbar">
							<div class="am-btn-group am-btn-group-xs">
								<a class="am-btn am-btn-default am-btn-xs" href="{% url 'dashboard:MentoringRecordListView' %}?student_id={{ user.id }}"><span class="am-icon-calendar"></span> 辅导纪录</a>
								<a class="am-btn am-btn-default am-btn-xs" href="{% url 'dashboard:StudentDetailView' user.id %}"><span class="am-icon-user"></span> 基本资料</a>
								{% if request.user.groups.first.name == "管理员" %}
								<a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="{% url 'dashboard:StudentUpdateView' user.id %}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
								<a class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only" href="{% url 'dashboard:StudentDeleteView' user.id %}"><span class="am-icon-trash-o"></span> 删除</a>
								{% endif %}
							</div>
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "dashboard/paginator.html" %}
	</div>
</div>
{% endblock %}

templates/dashboard/teacher_list.html
{% extends 'dashboard/dashboard.html' %}
{% block content %}
<div class="am-g">
	<div class="am-u-sm-12 am-u-md-6">
		<div class="am-btn-toolbar">
			<div class="am-btn-group am-btn-group-xs">
				<a class="am-btn am-btn-default" href="{{ page_add }}"><span class="am-icon-plus"></span> 新增</a>
			</div>
		</div>
	</div>
	<div class="am-u-sm-12 am-u-md-3">
		<form class="am-form" method="get" action="">
			<div class="am-input-group am-input-group-sm">
				<input type="text" class="am-form-field" value="{{search_text}}" name="search_text">
				<span class="am-input-group-btn">
					<input class="am-btn am-btn-default" type="submit" name="submit" value="搜索"/>
				</span>
			</div>
		</form>
	</div>
</div>

<div class="am-g">
	<div class="am-u-sm-12">
		<table class="am-table am-table-striped am-table-hover table-main">
			<thead>
				<tr>
					<th>使用者名称</th>
					<th>姓名</th>
					<th>电话</th>
					<th>电邮</th>
					<th>上次登入</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
				{% for user in object_list %}
				<tr>
					<td>{{ user.username }}</td>
					<td>{{ user.last_name }} {{ user.first_name }}</td>
					<td>{{ user.userprofile.phone }}</td>
					<td class="am-hide-sm-only">{{ user.email }}</td>
					<td class="am-hide-sm-only">
						{% if user.last_login %}{{ user.last_login }}{% else %}无{% endif %}
					</td>
					<td>
						<div class="am-btn-toolbar">
							<div class="am-btn-group am-btn-group-xs">
								<a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="{% url 'dashboard:TeacherUpdateView' user.id %}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
								<a class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only" href="{% url 'dashboard:TeacherDeleteView' user.id %}"><span class="am-icon-trash-o"></span> 删除</a>
							</div>
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "dashboard/paginator.html" %}
	</div>
</div>
{% endblock %}